# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impacto', '0002_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='area_FK',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='impacto.Area', verbose_name='Area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impactoprojeto',
            name='area_FK',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='impacto.Area', verbose_name='Area'),
            preserve_default=False,
        ),
    ]
