# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impacto', '0004_auto_20160606_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='projeto_FK',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='impacto.Projeto', verbose_name='Projeto'),
            preserve_default=False,
        ),
    ]
