# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impacto', '0005_area_projeto_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionariointerno',
            name='quadro_item_FK',
        ),
        migrations.AddField(
            model_name='questionariointerno',
            name='resp_potencial',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='RespPot', to='impacto.QuadroItem', verbose_name='Resposta Potencial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionariointerno',
            name='resp_provavel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='RespProv', to='impacto.QuadroItem', verbose_name='Resposta Provável'),
            preserve_default=False,
        ),
    ]
