# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impacto', '0006_auto_20160609_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactoprojeto',
            name='aia',
            field=models.CharField(default='', max_length=50, verbose_name='AIA'),
            preserve_default=False,
        ),
    ]
