# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impacto', '0007_impactoprojeto_aia'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadro',
            name='descricao_curta',
            field=models.TextField(default='', verbose_name='Descrição Curta'),
            preserve_default=False,
        ),
    ]
