# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impacto', '0013_auto_20160617_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questrespitem',
            name='quest_item_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='impacto.QuestaoItem', verbose_name='Resposta'),
        ),
    ]
